// RESTAURANT ACTIONS
export const LOAD_RESTAURANT_SUCCESS = 'LOAD_RESTAURANT_SUCCESS';

// LOGIN ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CREATE_USER = 'CREATE_USER';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const PASSWORD_SET_SUCCESS = 'PASSWORD_SET_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USER_VALIDATION_TOKEN = 'GET_USER_VALIDATION_TOKEN';

// SNACKBAR
export const SET_SNACKBAR_SUCCESS = 'SET_SNACKBAR_SUCCESS';
